In [4]:
import pandas as pd

In [8]:
df=pd.read_pickle('./data/all_stations_data.pkl').reset_index()
df.columns

Index(['index', 'REC_TIME', 'UNIT_ID', 'H1', 'H0', 'V', 'T0', 'T1', 'C1',
       'ERR', 'H2', 'T2', 'R', 'Rr', 'L0', 'L1'],
      dtype='object')

In [13]:
# select only station A07, dates from 2023-09-13 to 2023-09-15
dft=df[(df['UNIT_ID']=='A07') & (df['REC_TIME']>=pd.to_datetime('2023-09-13')) & (df['REC_TIME']<=pd.to_datetime('2023-09-16'))]
dft[:50]

,index,REC_TIME,UNIT_ID,H1,H0,V,T0,T1,C1,ERR,H2,T2,R,Rr,L0,L1
19012,19012,2023-09-13 01:00:00,A07,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN,NaN,597.0,NaN,NaN,NaN
19013,19013,2023-09-13 02:00:00,A07,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN,NaN,597.0,0.0,NaN,NaN
19014,19014,2023-09-13 03:00:00,A07,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN,NaN,597.0,0.0,NaN,NaN
19015,19015,2023-09-13 04:00:00,A07,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN,NaN,597.0,0.0,NaN,NaN
19016,19016,2023-09-13 05:00:00,A07,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN,NaN,597.0,0.0,NaN,NaN
19017,19017,2023-09-13 06:00:00,A07,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN,NaN,597.0,0.0,NaN,NaN
19018,19018,2023-09-13 07:00:00,A07,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN,NaN,597.0,0.0,NaN,NaN
19019,19019,2023-09-13 08:00:00,A07,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN,NaN,597.0,0.0,NaN,NaN
19020,19020,2023-09-13 09:00:00,A07,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN,NaN,597.0,0.0,NaN,NaN
19021,19021,2023-09-13 10:00:00,A07,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN,NaN,597.0,0.0,NaN,NaN
19022,19022,2023-09-13 11:00:00,A07,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN,NaN,597.0,0.0,NaN,NaN
19023,19023,2023-09-13 12:00:00,A07,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN,NaN,597.0,0.0,NaN,NaN
19024,19024,2023-09-13 13:00:00,A07,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN,NaN,597.0,0.0,NaN,NaN
19025,19025,2023-09-13 14:00:00,A07,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN,NaN,597.0,0.0,NaN,NaN
19026,19026,2023-09-13 15:00:00,A07,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN,NaN,597.0,0.0,NaN,NaN
19027,19027,2023-09-13 16:00:00,A07,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN,NaN,597.0,0.0,NaN,NaN
19028,19028,2023-09-13 17:00:00,A07,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN,NaN,597.0,0.0,NaN,NaN
19029,19029,2023-09-13 18:00:00,A07,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN,NaN,597.0,0.0,NaN,NaN
19030,19030,2023-09-13 19:00:00,A07,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN,NaN,597.0,0.0,NaN,NaN
19031,19031,2023-09-13 20:00:00,A07,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN,NaN,597.0,0.0,NaN,NaN
19032,19032,2023-09-13 21:00:00,A07,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN,NaN,597.0,0.0,NaN,NaN
19033,19033,2023-09-13 22:00:00,A07,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN,NaN,597.0,0.0,NaN,NaN
19034,19034,2023-09-13 23:00:00,A07,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN,NaN,597.0,0.0,NaN,NaN
19035,19035,2023-09-14 01:00:00,A07,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN,NaN,597.0,NaN,NaN,NaN
19036,19036,2023-09-14 02:00:00,A07,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN,NaN,597.0,0.0,NaN,NaN
19037,19037,2023-09-14 03:00:00,A07,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN,NaN,597.0,0.0,NaN,NaN
19038,19038,2023-09-14 04:00:00,A07,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN,NaN,597.0,0.0,NaN,NaN
19039,19039,2023-09-14 05:00:00,A07,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN,NaN,597.0,0.0,NaN,NaN
19040,19040,2023-09-14 06:00:00,A07,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN,NaN,597.8,0.8,NaN,NaN
19041,19041,2023-09-14 07:00:00,A07,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN,NaN,599.8,2.0,NaN,NaN
19042,19042,2023-09-14 08:00:00,A07,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN,NaN,600.0,0.2,NaN,NaN
19043,19043,2023-09-14 09:00:00,A07,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN,NaN,600.0,0.0,NaN,NaN
19044,19044,2023-09-14 10:00:00,A07,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN,NaN,600.0,0.0,NaN,NaN
19045,19045,2023-09-14 11:00:00,A07,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN,NaN,600.0,0.0,NaN,NaN
19046,19046,2023-09-14 12:00:00,A07,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN,NaN,601.2,1.2,NaN,NaN
19047,19047,2023-09-14 13:00:00,A07,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN,NaN,602.0,0.8,NaN,NaN
19048,19048,2023-09-14 14:00:00,A07,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN,NaN,602.2,0.2,NaN,NaN
19049,19049,2023-09-14 15:00:00,A07,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN,NaN,602.2,0.0,NaN,NaN
19050,19050,2023-09-14 16:00:00,A07,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN,NaN,602.2,0.0,NaN,NaN
19051,19051,2023-09-14 17:00:00,A07,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN,NaN,602.2,0.0,NaN,NaN
19052,19052,2023-09-14 18:00:00,A07,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN,NaN,602.2,0.0,NaN,NaN
19053,19053,2023-09-14 19:00:00,A07,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN,NaN,602.4,0.2,NaN,NaN
19054,19054,2023-09-14 20:00:00,A07,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN,NaN,602.4,0.0,NaN,NaN
19055,19055,2023-09-14 21:00:00,A07,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN,NaN,602.4,0.0,NaN,NaN
19056,19056,2023-09-14 22:00:00,A07,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN,NaN,602.4,0.0,NaN,NaN
19057,19057,2023-09-14 23:00:00,A07,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN,NaN,602.4,0.0,NaN,NaN
19058,19058,2023-09-15 01:00:00,A07,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN,NaN,602.4,NaN,NaN,NaN
19059,19059,2023-09-15 02:00:00,A07,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN,NaN,602.4,0.0,NaN,NaN
19060,19060,2023-09-15 03:00:00,A07,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN,NaN,602.4,0.0,NaN,NaN
19061,19061,2023-09-15 04:00:00,A07,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN,NaN,602.4,0.0,NaN,NaN

In [14]:
# select only station A07, dates from 2023-09-13 to 2023-09-15
dft2=df[(df['UNIT_ID']=='A03') & (df['REC_TIME']>=pd.to_datetime('2023-09-13')) & (df['REC_TIME']<=pd.to_datetime('2023-09-16'))]
dft2[:50]

,index,REC_TIME,UNIT_ID,H1,H0,V,T0,T1,C1,ERR,H2,T2,R,Rr,L0,L1
7026,7026,2023-09-13 01:00:00,A03,0.95,10.24,15.87,27.69,27.90,0.16,0.0,NaN,NaN,NaN,NaN,NaN,NaN
7027,7027,2023-09-13 02:00:00,A03,0.95,10.24,15.79,27.59,27.91,0.16,0.0,NaN,NaN,NaN,NaN,NaN,NaN
7028,7028,2023-09-13 03:00:00,A03,0.93,10.23,15.80,27.47,27.91,0.16,0.0,NaN,NaN,NaN,NaN,NaN,NaN
7029,7029,2023-09-13 04:00:00,A03,0.87,10.23,15.78,27.14,27.92,0.16,0.0,NaN,NaN,NaN,NaN,NaN,NaN
7030,7030,2023-09-13 05:00:00,A03,0.82,10.22,15.75,26.39,27.92,0.16,0.0,NaN,NaN,NaN,NaN,NaN,NaN
7031,7031,2023-09-13 06:00:00,A03,0.75,10.23,15.74,26.47,27.93,0.16,0.0,NaN,NaN,NaN,NaN,NaN,NaN
7032,7032,2023-09-13 07:00:00,A03,0.70,10.24,15.74,28.32,27.94,0.16,0.0,NaN,NaN,NaN,NaN,NaN,NaN
7033,7033,2023-09-13 08:00:00,A03,0.68,10.26,15.95,31.87,27.94,0.16,0.0,NaN,NaN,NaN,NaN,NaN,NaN
7034,7034,2023-09-13 09:00:00,A03,0.68,10.28,16.10,38.07,27.94,0.16,0.0,NaN,NaN,NaN,NaN,NaN,NaN
7035,7035,2023-09-13 10:00:00,A03,0.74,10.29,16.16,39.24,27.95,0.16,0.0,NaN,NaN,NaN,NaN,NaN,NaN
7036,7036,2023-09-13 11:00:00,A03,0.83,10.28,16.16,38.24,27.95,0.16,0.0,NaN,NaN,NaN,NaN,NaN,NaN
7037,7037,2023-09-13 12:00:00,A03,0.91,10.27,16.16,37.15,27.97,0.16,0.0,NaN,NaN,NaN,NaN,NaN,NaN
7038,7038,2023-09-13 13:00:00,A03,0.96,10.26,16.17,37.85,27.98,0.16,0.0,NaN,NaN,NaN,NaN,NaN,NaN
7039,7039,2023-09-13 14:00:00,A03,0.98,10.26,16.21,39.28,27.98,0.16,0.0,NaN,NaN,NaN,NaN,NaN,NaN
7040,7040,2023-09-13 15:00:00,A03,0.96,10.26,16.25,39.64,27.98,0.16,0.0,NaN,NaN,NaN,NaN,NaN,NaN
7041,7041,2023-09-13 16:00:00,A03,0.92,10.26,16.22,40.11,27.98,0.16,0.0,NaN,NaN,NaN,NaN,NaN,NaN
7042,7042,2023-09-13 17:00:00,A03,0.86,10.26,16.22,38.31,27.99,0.16,0.0,NaN,NaN,NaN,NaN,NaN,NaN
7043,7043,2023-09-13 18:00:00,A03,0.80,10.25,16.08,31.27,27.99,0.16,0.0,NaN,NaN,NaN,NaN,NaN,NaN
7044,7044,2023-09-13 19:00:00,A03,0.75,10.25,16.02,29.33,28.00,0.16,0.0,NaN,NaN,NaN,NaN,NaN,NaN
7045,7045,2023-09-13 20:00:00,A03,0.72,10.26,15.99,28.94,28.00,0.16,0.0,NaN,NaN,NaN,NaN,NaN,NaN
7046,7046,2023-09-13 21:00:00,A03,0.72,10.27,15.98,28.83,27.99,0.16,0.0,NaN,NaN,NaN,NaN,NaN,NaN
7047,7047,2023-09-13 22:00:00,A03,0.75,10.28,15.96,28.74,28.00,0.16,0.0,NaN,NaN,NaN,NaN,NaN,NaN
7048,7048,2023-09-13 23:00:00,A03,0.83,10.27,15.92,28.66,28.00,0.16,0.0,NaN,NaN,NaN,NaN,NaN,NaN
7049,7049,2023-09-14 01:00:00,A03,0.95,10.25,15.88,28.42,28.00,0.16,0.0,NaN,NaN,NaN,NaN,NaN,NaN
7050,7050,2023-09-14 02:00:00,A03,0.98,10.24,15.86,28.39,28.00,0.16,0.0,NaN,NaN,NaN,NaN,NaN,NaN
7051,7051,2023-09-14 03:00:00,A03,0.96,10.24,15.86,28.38,28.01,0.16,0.0,NaN,NaN,NaN,NaN,NaN,NaN
7052,7052,2023-09-14 04:00:00,A03,0.92,10.24,15.84,28.25,28.01,0.16,0.0,NaN,NaN,NaN,NaN,NaN,NaN
7053,7053,2023-09-14 05:00:00,A03,0.86,10.24,15.75,28.27,28.01,0.16,0.0,NaN,NaN,NaN,NaN,NaN,NaN
7054,7054,2023-09-14 06:00:00,A03,0.80,10.24,15.74,27.07,28.03,0.16,0.0,NaN,NaN,NaN,NaN,NaN,NaN
7055,7055,2023-09-14 07:00:00,A03,0.75,10.25,15.84,27.17,28.02,0.16,0.0,NaN,NaN,NaN,NaN,NaN,NaN
7056,7056,2023-09-14 08:00:00,A03,0.71,10.26,15.90,28.15,28.03,0.16,0.0,NaN,NaN,NaN,NaN,NaN,NaN
7057,7057,2023-09-14 09:00:00,A03,0.72,10.26,16.00,29.78,28.03,0.16,0.0,NaN,NaN,NaN,NaN,NaN,NaN
7058,7058,2023-09-14 10:00:00,A03,0.77,10.27,16.10,33.12,28.03,0.16,0.0,NaN,NaN,NaN,NaN,NaN,NaN
7059,7059,2023-09-14 11:00:00,A03,0.85,10.26,16.05,32.38,28.03,0.16,0.0,NaN,NaN,NaN,NaN,NaN,NaN
7060,7060,2023-09-14 12:00:00,A03,0.96,10.24,16.02,29.60,28.04,0.16,0.0,NaN,NaN,NaN,NaN,NaN,NaN
7061,7061,2023-09-14 13:00:00,A03,1.03,10.23,16.00,28.40,28.03,0.16,0.0,NaN,NaN,NaN,NaN,NaN,NaN
7062,7062,2023-09-14 14:00:00,A03,1.05,10.23,16.04,28.40,28.02,0.16,0.0,NaN,NaN,NaN,NaN,NaN,NaN
7063,7063,2023-09-14 15:00:00,A03,1.04,10.23,16.02,29.75,28.02,0.16,0.0,NaN,NaN,NaN,NaN,NaN,NaN
7064,7064,2023-09-14 16:00:00,A03,1.01,10.23,15.99,28.98,28.02,0.16,0.0,NaN,NaN,NaN,NaN,NaN,NaN
7065,7065,2023-09-14 17:00:00,A03,0.95,10.22,15.95,28.45,28.02,0.16,0.0,NaN,NaN,NaN,NaN,NaN,NaN
7066,7066,2023-09-14 18:00:00,A03,0.88,10.22,15.92,28.20,28.02,0.16,0.0,NaN,NaN,NaN,NaN,NaN,NaN
7067,7067,2023-09-14 19:00:00,A03,0.80,10.24,15.89,28.21,28.02,0.16,0.0,NaN,NaN,NaN,NaN,NaN,NaN
7068,7068,2023-09-14 20:00:00,A03,0.76,10.24,15.87,27.99,28.03,0.16,0.0,NaN,NaN,NaN,NaN,NaN,NaN
7069,7069,2023-09-14 21:00:00,A03,0.74,10.25,15.87,28.03,28.03,0.16,0.0,NaN,NaN,NaN,NaN,NaN,NaN
7070,7070,2023-09-14 22:00:00,A03,0.78,10.25,15.80,27.97,28.03,0.16,0.0,NaN,NaN,NaN,NaN,NaN,NaN
7071,7071,2023-09-14 23:00:00,A03,0.85,10.24,15.80,28.10,28.03,0.16,0.0,NaN,NaN,NaN,NaN,NaN,NaN
7072,7072,2023-09-15 01:00:00,A03,1.00,10.22,15.74,27.98,28.03,0.16,0.0,NaN,NaN,NaN,NaN,NaN,NaN
7073,7073,2023-09-15 02:00:00,A03,1.02,10.23,15.74,27.96,28.04,0.16,0.0,NaN,NaN,NaN,NaN,NaN,NaN
7074,7074,2023-09-15 03:00:00,A03,1.03,10.22,15.70,28.04,28.04,0.16,0.0,NaN,NaN,NaN,NaN,NaN,NaN
7075,7075,2023-09-15 04:00:00,A03,1.00,10.22,15.68,28.11,28.04,0.16,0.0,NaN,NaN,NaN,NaN,NaN,NaN